language: java
sudo: required
services:
  - docker

branches:
  - master

before_install:
  - echo TODO Setup Artifactory credentials
  - sudo apt-get update -qq

install:
  - echo TODO install debian package of CI Scripts.

script:
  - ./gradlew build
  - |-
    docker build \
    --build-arg version="$(./gradlew -q printVersion)" \
    --build-arg war="$(./gradlew -q printWarName)" \
    --build-arg jar="$(./gradlew -q printJettyRunnerName)" \
    -t crispy-barnacle:latest .
